function [ datapoints, change_points ] = load_sin_wave_data( data_length, segment_amplitudes, segment_snrs )
%LOAD_SIN_WAVE_DATA Load data generated by a sine wave
%   This function generates data of length DATA_LENGTH (default 1000), 
%   as generated by sine wave(s).
%   The segments are defined by SEGMENT_AMPLITUDES and SEGMENT_SNRS.
%   The first is a vector is amplitudes.
%   The latter is a vector which indicates the signal-to-noise ratio
%   (modellen by gaussian-white-noise).


    if nargin < 1
        data_length = 1000;
    end
    
    if nargin < 2
        segment_amplitudes = [1 3 1 5 2];
    end
    
    if nargin < 3
%         segment_snrs = [0.01 0.01 0.1 0.1 0.1];
        segment_snrs = [0 0 0 0 0];
    end

    if length(segment_amplitudes) ~= length(segment_snrs)
        return;
    end
    
    datapoints = zeros(data_length, 1);
    change_points = zeros(length(segment_amplitudes), 1);
    
    per_segment = ceil(data_length/ length(segment_amplitudes));
    i = 1;
    for segment = 1 : length(segment_amplitudes)
        t = 1:per_segment;
        a = segment_amplitudes(segment);
        
        f = 100;
        
        y = awgn(a * sin(2 * pi * f * t), segment_snrs(segment));
        
        datapoints(i:i+length(y)-1) = y;
        change_points(segment) = ((segment - 1) * per_segment) + 1;
        i = i + length(y);
    end

end

